/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Unauthenticated. Returns server status + timestamp.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/v1/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * login
         * @description **External Supabase Auth (GoTrue) endpoint — NOT part of the RoundFlow backend.** Returns an `access_token` (ES256 JWT). Copy it into **Authorize** (top-right) to call the protected endpoints below. The `apikey` header is the Supabase anon (publishable) key, prefilled here.
         */
        post: {
            parameters: {
                query: {
                    grant_type: "password";
                };
                header: {
                    /** @description Supabase anon (publishable) key. */
                    apikey: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SupabaseLoginInput"];
                };
            };
            responses: {
                /** @description Session — contains `access_token`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupabaseSession"];
                    };
                };
                /** @description Auth error (Supabase error shape varies). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user's profile
         * @description Returns the Profile for the authenticated caller (looked up by supabaseUserId from the JWT `sub`). 404 if no Profile exists.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller's Profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description No Profile for this user. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Setup progress
         * @description Per-step completion (derived, not stored) plus `setupCompleted` and `allRequiredComplete`. Required steps: 1,2,3,4,6,7,8. Only step 5 (SMS Templates) is deferred.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current setup status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetupStatus"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/step/1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Step 1 — get Business Profile
         * @description Returns the BusinessSettings singleton (or null if not yet created). Open after setup completes — the Settings screens reuse it.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description BusinessSettings (or null). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"] | null;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Step 1 — Business Profile
         * @description Upserts the BusinessSettings singleton. `businessName` is required.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BusinessProfileInput"];
                };
            };
            responses: {
                /** @description The updated BusinessSettings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/step/2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Step 2 — get Payment Setup
         * @description Returns the BusinessSettings singleton (read `paymentRule`, `debtHoldEnabled`, `vatInInvoices`, `gocardlessConnected`, `stripeConnected`). Open after setup completes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description BusinessSettings (or null). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"] | null;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Step 2 — Payment Setup
         * @description Upserts payment configuration on the BusinessSettings singleton. All fields optional; step 2 counts as complete once `paymentRule` is set. The GoCardless/Stripe connect actions are **Phase-1 stubs** (`gocardlessConnected`/`stripeConnected` are plain booleans — no real OAuth yet).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentSetupInput"];
                };
            };
            responses: {
                /** @description The updated BusinessSettings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/step/3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Step 3 — list services */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current service catalogue. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Service"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Step 3 — create/replace the service catalogue
         * @description REPLACES the whole catalogue with the posted list (existing services are cleared first). Send everything you want to keep.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceInput"][] | {
                        services: components["schemas"]["ServiceInput"][];
                    };
                };
            };
            responses: {
                /** @description The new catalogue. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Service"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/step/4": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Step 4 — get Round Settings
         * @description Returns the BusinessSettings singleton (same row as step 1; read `defaultCycleLength` / `defaultWorkingDays`). Open after setup completes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description BusinessSettings (or null). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"] | null;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Step 4 — Round Settings
         * @description Upserts BusinessSettings. `defaultCycleLength` is required (days).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoundSettingsInput"];
                };
            };
            responses: {
                /** @description The updated BusinessSettings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/step/5": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Step 5 — SMS Templates (deferred) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deferred stub. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeferredStub"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Step 5 — SMS Templates (deferred, no-op)
         * @description Deferred stub — performs no DB write.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deferred stub — no DB write. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeferredStub"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/step/6": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Step 6 — list technicians */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Technicians. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Technician"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Step 6 — save invite-pending technician(s)
         * @description REPLACES all invite-pending technicians (profileId = null) with the posted list — send the full list you want to keep (re-posting is safe; it does not append duplicates). Technicians who have accepted an invite (real profileId) are never affected. Each created technician is invite-pending (profileId = null).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianInput"][] | {
                        technicians: components["schemas"]["TechnicianInput"][];
                    };
                };
            };
            responses: {
                /** @description All technicians. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Technician"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/step/7": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Step 7 — list service areas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service areas. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceArea"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Step 7 — save service area(s)
         * @description REPLACES all service areas with the posted list — send the full list you want to keep (re-posting is safe; it does not append duplicates).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceAreaInput"][] | {
                        serviceAreas: components["schemas"]["ServiceAreaInput"][];
                    };
                };
            };
            responses: {
                /** @description All service areas. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceArea"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/step/8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Step 8 — list ACTIVE rounds */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ACTIVE rounds. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Round"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Step 8 — save the first round (ACTIVE)
         * @description Creates OR updates the single setup round (upsert) — re-posting updates the existing ACTIVE round rather than creating a second. The round is ACTIVE. `name` required; `defaultDay`/`frequency` validated against their enums; `serviceAreaId` (if given) must exist.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FirstRoundInput"];
                };
            };
            responses: {
                /** @description The created round. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Round"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete setup
         * @description Marks setup complete. Requires all non-deferred steps (1,2,3,4,6,7,8). After completion, mutating step endpoints return 403.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Final status (setupCompleted = true). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetupStatus"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/business-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get business profile
         * @description Returns the BusinessSettings singleton (or null).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description BusinessSettings (or null). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"] | null;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update business profile (partial)
         * @description Partial upsert of step-1 fields (businessName, phone, email, companyNumber, vatRegistered, vatRegistration, timezone, currency, defaultWorkingDays). Omitted = untouched; null clears. Does not touch round-settings fields.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BusinessProfileUpdateInput"];
                };
            };
            responses: {
                /** @description Updated BusinessSettings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/settings/round-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get round settings
         * @description Returns the BusinessSettings singleton; read `defaultCycleLength` / `defaultWorkingDays`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description BusinessSettings (or null). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"] | null;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update round settings (partial)
         * @description Partial upsert of round fields only (`defaultCycleLength`, `defaultWorkingDays`).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoundSettingsUpdateInput"];
                };
            };
            responses: {
                /** @description Updated BusinessSettings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/settings/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List services */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All services. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Service"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a service */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceCreateInput"];
                };
            };
            responses: {
                /** @description The created service. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Service"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a service
         * @description 409 if any ServicePlan or Visit references the service.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /** Update a service (partial) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceUpdateInput"];
                };
            };
            responses: {
                /** @description The updated service. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Service"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/settings/service-areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List service areas (with linkedRounds)
         * @description Each area includes a derived, read-only `linkedRounds` summary.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All service areas. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceAreaWithRounds"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a service area */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceAreaCreateInput"];
                };
            };
            responses: {
                /** @description The created service area. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceArea"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/service-areas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a service area
         * @description 409 if any Round or Property references the area.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /** Update a service area (partial) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceAreaUpdateInput"];
                };
            };
            responses: {
                /** @description The updated service area. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceArea"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/settings/technicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List technicians (with displayName + appStatus) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All technicians. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TechnicianWithDisplayName"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create an invite-pending technician */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianCreateInput"];
                };
            };
            responses: {
                /** @description The created technician. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Technician"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/technicians/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a technician
         * @description Only invite-pending technicians (profileId = null) can be deleted; 409 if the invite was accepted.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /** Update a technician (partial) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechnicianUpdateInput"];
                };
            };
            responses: {
                /** @description The updated technician. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Technician"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/settings/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payment setup
         * @description Returns the BusinessSettings singleton; read the payment fields.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description BusinessSettings (or null). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"] | null;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update payment rules (partial)
         * @description Updates `paymentRule` / `vatInInvoices` / `debtHoldEnabled` only. Does NOT touch the connect flags — use the connect endpoint for those.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentRulesUpdateInput"];
                };
            };
            responses: {
                /** @description Updated BusinessSettings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessSettings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/settings/payment/{provider}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "gocardless" | "stripe";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect a payment provider (Phase-1 stub)
         * @description Phase-1 stub: flips the relevant *Connected boolean to true and returns `{ status: "connected" }`. No OAuth / no URL yet — a real `connectUrl` will come from GHL in Phase 2.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "gocardless" | "stripe";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connection result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderConnectResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/message-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SMS templates (deferred)
         * @description Deferred — GHL owns messaging in Phase 2. No DB access.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deferred stub. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageTemplateDeferred"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * SMS templates (deferred, no-op)
         * @description Deferred — returns the same payload, performs no DB write.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deferred stub. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageTemplateDeferred"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List customers + summary KPIs (Screen 14)
         * @description Search + filter. `?search=` matches name/addressLine/postcode (case-insensitive contains); `?roundId=` filters by assigned round; `?status=` ∈ ACTIVE|PAUSED|CANCELLED|HOLD (HOLD is derived from paymentHold visits). Summary KPIs are business-wide (not filtered).
         */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    roundId?: string;
                    status?: "ACTIVE" | "PAUSED" | "CANCELLED" | "HOLD";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List + summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerListResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Full Customer Detail aggregate (Screen 15 — all 6 tabs in one call) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer Detail aggregate. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** M19 — Edit Customer Record (Customer + Property + Plan, atomic) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CustomerUpdateInput"];
                };
            };
            responses: {
                /** @description Updated ids. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            customerId?: string;
                            propertyId?: string | null;
                            servicePlanId?: string | null;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * M6 — Add Property (creates Customer + Property + ServicePlan, atomic)
         * @description The only way customers are created (there is no POST /customers). `roundId: null` = Save & Assign Later (unassigned).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PropertyCreateInput"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            customerId?: string;
                            propertyId?: string;
                            servicePlanId?: string;
                            assigned?: boolean;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update property (+ Move Round: assign/unassign) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PropertyUpdateInput"];
                };
            };
            responses: {
                /** @description Updated property. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/properties/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * M9 — Pause Service (ServicePlan.status → PAUSED)
         * @description 409 if the plan is already PAUSED. `reason` is validated but not persisted (no column).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PauseServiceInput"];
                };
            };
            responses: {
                /** @description Updated ServicePlan. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Service (status → ACTIVE, clears pause window)
         * @description 409 if the plan is not currently PAUSED.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated ServicePlan. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List notes (Notes & Risk), newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyNote"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** M20 — Add Note (author = acting Profile) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NoteCreateInput"];
                };
            };
            responses: {
                /** @description Created note. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyNote"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        UserRole: "ADMIN" | "MANAGER" | "TECHNICIAN";
        /** @enum {string} */
        LifecycleStatus: "ACTIVE" | "PAUSED" | "CANCELLED";
        /** @enum {string} */
        RoundStatus: "ACTIVE" | "DRAFT" | "ARCHIVED";
        /** @enum {string} */
        DayOfWeek: "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";
        /** @enum {string} */
        CleaningFrequency: "FORTNIGHTLY" | "FOUR_WEEKLY" | "SIX_WEEKLY" | "EIGHT_WEEKLY" | "MONTHLY";
        /** @enum {string} */
        VisitStatus: "SCHEDULED" | "IN_PROGRESS" | "COMPLETED" | "SKIPPED";
        /** @enum {string} */
        PaymentStatus: "NOT_DUE" | "PENDING" | "PAID" | "FAILED" | "OVERDUE";
        /** @enum {string} */
        PaymentMethod: "GOCARDLESS" | "CASH" | "CHEQUE" | "BACS" | "STRIPE";
        /** @enum {string} */
        MessageChannel: "SMS" | "WHATSAPP" | "EMAIL";
        /** @enum {string} */
        MessageDirection: "OUTBOUND" | "INBOUND";
        /** @enum {string} */
        Severity: "LOW" | "MEDIUM" | "HIGH";
        /** @enum {string} */
        ComplaintStatus: "OPEN" | "IN_REVIEW" | "REVISIT_BOOKED" | "RESOLVED";
        /** @enum {string} */
        ServiceCategory: "DEFAULT" | "WINDOW_CLEANING" | "GUTTER_FASCIA" | "EXTERIOR_CLEANING" | "SPECIALIST";
        /** @enum {string} */
        InvoiceStatus: "DRAFT" | "SENT" | "PAID";
        /** @enum {string} */
        IssueType: "ACCESS_PROBLEM" | "GATE_LOCKED" | "PAYMENT_ISSUE" | "OTHER";
        /** @enum {string} */
        PhotoType: "PROPERTY" | "BEFORE" | "AFTER";
        /** @enum {string} */
        PaymentTiming: "COLLECT_AFTER_VISIT" | "COLLECT_BEFORE_VISIT" | "COLLECT_ON_DATE";
        /** @enum {string} */
        NoteType: "INTERNAL" | "RISK_WARNING" | "CUSTOMER";
        /**
         * @example {
         *       "error": "Unauthorized"
         *     }
         */
        Error: {
            error: string;
        };
        /**
         * @description Public-schema mirror of a Supabase auth.users record.
         * @example {
         *       "id": "6d432b38-676d-4791-b486-2be40a1dea7e",
         *       "supabaseUserId": "87d11631-fdcb-41b7-8484-2431dc3feb56",
         *       "role": "ADMIN",
         *       "name": "maazk101103",
         *       "createdAt": "2026-07-01T23:29:00.354Z",
         *       "updatedAt": "2026-07-01T23:29:00.354Z"
         *     }
         */
        Profile: {
            id: string;
            /** @description → auth.users.id */
            supabaseUserId: string;
            role: components["schemas"]["UserRole"];
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description The single business config row (Phase 1 is single-tenant). */
        BusinessSettings: {
            id?: string;
            /** @example singleton */
            uniqueId?: string;
            businessName?: string | null;
            phone?: string | null;
            email?: string | null;
            companyNumber?: string | null;
            vatRegistration?: string | null;
            vatRegistered?: boolean;
            defaultWorkingDays?: string[];
            timezone?: string | null;
            currency?: string | null;
            /** @description Cycle length in days. */
            defaultCycleLength?: number | null;
            bankDetails?: {
                [key: string]: unknown;
            } | null;
            paymentRule?: components["schemas"]["PaymentTiming"] | null;
            debtHoldEnabled?: boolean;
            vatInInvoices?: boolean;
            gocardlessConnected?: boolean;
            stripeConnected?: boolean;
            setupCompleted?: boolean;
            /** Format: date-time */
            updatedAt?: string;
        };
        Service: {
            id?: string;
            name?: string;
            category?: components["schemas"]["ServiceCategory"];
            description?: string | null;
            /**
             * @description Decimal money value serialised as a string, e.g. "35".
             * @example 35
             */
            defaultPrice?: string;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description A field operative. Invite-pending rows have profileId = null until the invite is accepted. */
        Technician: {
            id?: string;
            profileId?: string | null;
            /** @description Admin display label; Profile.name wins once the invite is accepted. */
            name?: string | null;
            /** @description Operational role, e.g. Senior. */
            role?: string | null;
            phone?: string | null;
            active?: boolean;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description A geographic service area. Note: no updatedAt field. */
        ServiceArea: {
            id?: string;
            name?: string;
            postcodeSector?: string | null;
            isDefault?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        Round: {
            id?: string;
            name?: string;
            defaultDay?: components["schemas"]["DayOfWeek"] | null;
            frequency?: components["schemas"]["CleaningFrequency"] | null;
            description?: string | null;
            status?: components["schemas"]["RoundStatus"];
            serviceAreaId?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ServiceAreaWithRounds: components["schemas"]["ServiceArea"] & {
            /** @description Derived, read-only summary of Rounds referencing this area. */
            linkedRounds?: {
                count?: number;
                names?: string[];
            };
        };
        TechnicianWithDisplayName: components["schemas"]["Technician"] & {
            profile?: components["schemas"]["Profile"] | null;
            /** @description profile?.name ?? technician.name ?? null. */
            displayName?: string | null;
            /** @enum {string} */
            appStatus?: "PENDING_INVITE" | "ACTIVE" | "INACTIVE";
        };
        ProviderConnectResponse: {
            /** @example connected */
            status: string;
            /** @description Phase-1 stub returns no URL; a real URL comes from GHL in Phase 2. */
            connectUrl?: string | null;
        };
        MessageTemplateDeferred: {
            /** @enum {string} */
            status: "deferred";
            /** @example ghl */
            source: string;
        };
        StepStatus: {
            step: number;
            complete: boolean;
            /** @description True for step 5 (SMS Templates). Step 2 (Payment Setup) is now a real step. */
            deferred: boolean;
        };
        /**
         * @example {
         *       "setupCompleted": false,
         *       "allRequiredComplete": false,
         *       "steps": [
         *         {
         *           "step": 1,
         *           "complete": false,
         *           "deferred": false
         *         },
         *         {
         *           "step": 2,
         *           "complete": false,
         *           "deferred": false
         *         },
         *         {
         *           "step": 3,
         *           "complete": false,
         *           "deferred": false
         *         },
         *         {
         *           "step": 4,
         *           "complete": false,
         *           "deferred": false
         *         },
         *         {
         *           "step": 5,
         *           "complete": false,
         *           "deferred": true
         *         },
         *         {
         *           "step": 6,
         *           "complete": false,
         *           "deferred": false
         *         },
         *         {
         *           "step": 7,
         *           "complete": false,
         *           "deferred": false
         *         },
         *         {
         *           "step": 8,
         *           "complete": false,
         *           "deferred": false
         *         }
         *       ]
         *     }
         */
        SetupStatus: {
            setupCompleted: boolean;
            /** @description True when every non-deferred step (1,2,3,4,6,7,8) is complete. */
            allRequiredComplete: boolean;
            steps: components["schemas"]["StepStatus"][];
        };
        DeferredStub: {
            /** @enum {string} */
            status: "deferred";
            reason: string;
        };
        HealthStatus: {
            /** @example ok */
            status: string;
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * @example {
         *       "email": "you@example.com",
         *       "password": "your-password"
         *     }
         */
        SupabaseLoginInput: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        /** @description Supabase session. Use `access_token` as the Bearer token. */
        SupabaseSession: {
            /** @description ES256 JWT — paste into Authorize as the Bearer token. */
            access_token?: string;
            /** @example bearer */
            token_type?: string;
            /** @example 3600 */
            expires_in?: number;
            expires_at?: number;
            refresh_token?: string;
            /** @description The Supabase user object. */
            user?: {
                [key: string]: unknown;
            };
        };
        /**
         * @example {
         *       "businessName": "Acme Window Co",
         *       "phone": "+44 1665 111111",
         *       "vatRegistered": true,
         *       "defaultWorkingDays": [
         *         "MON",
         *         "TUE",
         *         "WED",
         *         "THU",
         *         "FRI"
         *       ],
         *       "timezone": "Europe/London",
         *       "currency": "GBP"
         *     }
         */
        BusinessProfileInput: {
            businessName: string;
            phone?: string;
            email?: string;
            companyNumber?: string;
            vatRegistered?: boolean;
            vatRegistration?: string;
            defaultWorkingDays?: string[];
            timezone?: string;
            currency?: string;
        };
        /**
         * @example {
         *       "defaultCycleLength": 28
         *     }
         */
        RoundSettingsInput: {
            /** @description Cycle length in days. */
            defaultCycleLength: number;
            defaultWorkingDays?: string[];
        };
        /**
         * @description Setup step 2 (Payment Setup). All fields optional. Connect toggles are Phase-1 stubs (booleans; no real OAuth).
         * @example {
         *       "paymentRule": "COLLECT_AFTER_VISIT",
         *       "debtHoldEnabled": true,
         *       "vatInInvoices": true
         *     }
         */
        PaymentSetupInput: {
            /**
             * @description Default payment collection rule.
             * @enum {string}
             */
            paymentRule?: "COLLECT_AFTER_VISIT" | "COLLECT_BEFORE_VISIT" | "COLLECT_ON_DATE";
            /** @description Block service if payment is overdue. */
            debtHoldEnabled?: boolean;
            /** @description Include VAT in invoices by default. */
            vatInInvoices?: boolean;
            /** @description GoCardless connection flag (Phase-1 stub). */
            gocardlessConnected?: boolean;
            /** @description Stripe connection flag (Phase-1 stub). */
            stripeConnected?: boolean;
        };
        /**
         * @example {
         *       "name": "Full exterior window clean",
         *       "category": "WINDOW_CLEANING",
         *       "defaultPrice": 35,
         *       "active": true
         *     }
         */
        ServiceInput: {
            name: string;
            /** @description Sent as a number; returned as a string. */
            defaultPrice: number;
            category?: components["schemas"]["ServiceCategory"];
            description?: string;
            active?: boolean;
        };
        /**
         * @description Creates an invite-pending technician (profileId = null).
         * @example {
         *       "name": "James Fisher",
         *       "role": "Senior",
         *       "phone": "+44 7700 900111"
         *     }
         */
        TechnicianInput: {
            /** @description Admin display label ('invited as…'); persisted to Technician.name. Profile.name wins once the invite is accepted. */
            name?: string;
            role?: string;
            phone?: string;
            active?: boolean;
        };
        /**
         * @example {
         *       "name": "Alnwick",
         *       "postcodeSector": "NE66",
         *       "isDefault": true
         *     }
         */
        ServiceAreaInput: {
            name: string;
            postcodeSector?: string;
            isDefault?: boolean;
        };
        /**
         * @example {
         *       "name": "Alnwick Monday",
         *       "defaultDay": "MON",
         *       "frequency": "FOUR_WEEKLY",
         *       "serviceAreaId": "clx..."
         *     }
         */
        FirstRoundInput: {
            name: string;
            defaultDay?: components["schemas"]["DayOfWeek"];
            frequency?: components["schemas"]["CleaningFrequency"];
            serviceAreaId?: string;
        };
        /**
         * @description Partial update — all fields optional. Step-1 fields only; does not touch round-settings fields.
         * @example {
         *       "businessName": "Northumberland Window Cleaning",
         *       "currency": "GBP"
         *     }
         */
        BusinessProfileUpdateInput: {
            businessName?: string | null;
            phone?: string | null;
            email?: string | null;
            companyNumber?: string | null;
            vatRegistered?: boolean;
            vatRegistration?: string | null;
            timezone?: string | null;
            currency?: string | null;
            defaultWorkingDays?: string[];
        };
        /**
         * @description Partial update — round-settings fields only.
         * @example {
         *       "defaultCycleLength": 28
         *     }
         */
        RoundSettingsUpdateInput: {
            /** @description Cycle length in days. */
            defaultCycleLength?: number | null;
            defaultWorkingDays?: string[];
        };
        /**
         * @example {
         *       "name": "Gutter clear",
         *       "category": "GUTTER_FASCIA",
         *       "defaultPrice": 60
         *     }
         */
        ServiceCreateInput: {
            name: string;
            /** @description Sent as a number; returned as a string. */
            defaultPrice: number;
            category?: components["schemas"]["ServiceCategory"];
            description?: string | null;
            active?: boolean;
        };
        /** @description Partial update — all fields optional. */
        ServiceUpdateInput: {
            name?: string;
            defaultPrice?: number;
            category?: components["schemas"]["ServiceCategory"];
            description?: string | null;
            active?: boolean;
        };
        /**
         * @example {
         *       "name": "Morpeth",
         *       "postcodeSector": "NE61"
         *     }
         */
        ServiceAreaCreateInput: {
            name: string;
            postcodeSector?: string | null;
            isDefault?: boolean;
        };
        /** @description Partial update — all fields optional. */
        ServiceAreaUpdateInput: {
            name?: string;
            postcodeSector?: string | null;
            isDefault?: boolean;
        };
        /**
         * @description Single invite-pending technician (profileId = null).
         * @example {
         *       "name": "James Fisher",
         *       "role": "Senior",
         *       "phone": "+44 7700 900111"
         *     }
         */
        TechnicianCreateInput: {
            /** @description Admin display label. */
            name?: string | null;
            phone?: string | null;
            role?: string | null;
            active?: boolean;
        };
        /** @description Partial update — all fields optional. */
        TechnicianUpdateInput: {
            name?: string | null;
            phone?: string | null;
            role?: string | null;
            active?: boolean;
        };
        /**
         * @description Partial update of payment RULES only — does not touch the connect flags.
         * @example {
         *       "paymentRule": "COLLECT_AFTER_VISIT",
         *       "vatInInvoices": true
         *     }
         */
        PaymentRulesUpdateInput: {
            paymentRule?: components["schemas"]["PaymentTiming"] | null;
            vatInInvoices?: boolean;
            debtHoldEnabled?: boolean;
        };
        Property: {
            id?: string;
            customerId?: string;
            propertyName?: string | null;
            addressLine?: string;
            postcode?: string;
            serviceAreaId?: string | null;
            propertyType?: string | null;
            accessNotes?: string | null;
            riskNotes?: string | null;
            status?: components["schemas"]["LifecycleStatus"];
            roundId?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PropertyNote: {
            id?: string;
            propertyId?: string;
            type?: components["schemas"]["NoteType"];
            body?: string;
            authorProfileId?: string | null;
            /** @description Derived from the author Profile (list/detail reads). */
            authorName?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        ServicePlanView: {
            id?: string;
            serviceId?: string | null;
            serviceName?: string | null;
            /** @description Numeric (Decimal serialised to a number here, unlike raw money-string fields). */
            price?: number | null;
            cleanMethod?: string | null;
            paymentMethod?: components["schemas"]["PaymentMethod"] | null;
            status?: components["schemas"]["LifecycleStatus"];
            /** Format: date-time */
            nextDueDate?: string | null;
            /** Format: date-time */
            lastCompleted?: string | null;
            /** Format: date-time */
            pauseStartDate?: string | null;
            /** Format: date-time */
            pauseEndDate?: string | null;
            paymentRule?: components["schemas"]["PaymentTiming"] | null;
        };
        CustomerListRow: {
            customerId?: string;
            customerName?: string;
            status?: components["schemas"]["LifecycleStatus"];
            propertyId?: string;
            addressLine?: string;
            postcode?: string;
            roundId?: string | null;
            roundName?: string | null;
            frequency?: components["schemas"]["CleaningFrequency"] | null;
            price?: number | null;
            technicianId?: string | null;
            technicianName?: string | null;
            /** Format: date-time */
            nextDueDate?: string | null;
            /** @enum {string} */
            paymentStatus?: "paid" | "hold" | "pending" | "overdue" | "failed";
            onHold?: boolean;
            amountDue?: number;
        };
        CustomerListResult: {
            summary?: {
                totalCustomers?: number;
                active?: number;
                paymentHolds?: number;
                amountDue?: number;
            };
            customers?: components["schemas"]["CustomerListRow"][];
        };
        VisitHistoryRow: {
            visitId?: string;
            /** Format: date-time */
            date?: string;
            roundName?: string | null;
            status?: components["schemas"]["VisitStatus"];
            paymentStatus?: components["schemas"]["PaymentStatus"] | null;
            notes?: string | null;
        };
        PaymentRow: {
            visitId?: string;
            /** Format: date-time */
            visitDate?: string;
            technicianName?: string | null;
            amount?: number | null;
            paymentStatus?: components["schemas"]["PaymentStatus"] | null;
            paymentId?: string | null;
            invoiceStatus?: components["schemas"]["InvoiceStatus"] | null;
            invoiceId?: string | null;
            invoiceNumber?: string | null;
            /** @description Payment.gocardlessId ?? stripeId. */
            transactionId?: string | null;
            canGenerate?: boolean;
            canDownload?: boolean;
        };
        /** @description Full Customer Detail aggregate (Screen 15, all 6 tabs). Phase 1: one active property per customer; round/technician/next-visit fields are null when the property is unassigned (Property.roundId = null). */
        CustomerDetail: {
            customer?: {
                id?: string;
                name?: string;
                phone?: string | null;
                email?: string | null;
                status?: components["schemas"]["LifecycleStatus"];
                ghlContactId?: string | null;
            };
            property?: {
                id?: string;
                addressLine?: string;
                postcode?: string;
                propertyType?: string | null;
                accessNotes?: string | null;
                riskNotes?: string | null;
                status?: components["schemas"]["LifecycleStatus"];
                roundId?: string | null;
                roundName?: string | null;
                serviceAreaId?: string | null;
            } | null;
            servicePlan?: components["schemas"]["ServicePlanView"] | null;
            standingInfo?: {
                frequency?: components["schemas"]["CleaningFrequency"] | null;
                assignedRound?: string | null;
                technicianName?: string | null;
                paymentStatus?: string;
                outstandingBalance?: number;
                /** Format: date-time */
                lastPaymentDate?: string | null;
                issuesCount?: number;
                nextVisitStatus?: components["schemas"]["VisitStatus"] | null;
            };
            tabs?: {
                overview?: {
                    [key: string]: unknown;
                } | null;
                servicePlan?: components["schemas"]["ServicePlanView"] | null;
                visitHistory?: components["schemas"]["VisitHistoryRow"][];
                payments?: {
                    rows?: components["schemas"]["PaymentRow"][];
                };
                notes?: components["schemas"]["PropertyNote"][];
                photos?: {
                    [key: string]: unknown;
                }[];
            };
        };
        /**
         * @example {
         *       "customerName": "John Smith",
         *       "addressLine": "12 Market Street",
         *       "postcode": "NE66 1SS",
         *       "price": 35,
         *       "cleanMethod": "Water Fed Pole",
         *       "paymentMethod": "GOCARDLESS",
         *       "roundId": null
         *     }
         */
        PropertyCreateInput: {
            customerName: string;
            phone?: string | null;
            email?: string | null;
            addressLine: string;
            postcode: string;
            propertyName?: string | null;
            propertyType?: string | null;
            /** @description Must exist (404 if not). */
            serviceAreaId?: string | null;
            serviceId?: string | null;
            /** @description Positive number. */
            price: number;
            cleanMethod?: string | null;
            paymentMethod?: components["schemas"]["PaymentMethod"] | null;
            /** Format: date */
            nextDueDate?: string | null;
            accessNotes?: string | null;
            riskNotes?: string | null;
            /** @description null = Save & Assign Later (unassigned); an id must exist (404 if not). */
            roundId?: string | null;
        };
        /** @description Partial update. roundId: null = unassign, an id = assign/reassign (Move Round). */
        PropertyUpdateInput: {
            addressLine?: string;
            postcode?: string;
            propertyName?: string | null;
            propertyType?: string | null;
            serviceAreaId?: string | null;
            accessNotes?: string | null;
            riskNotes?: string | null;
            roundId?: string | null;
        };
        /** @description M19 Edit Customer Record — partial update across Customer + Property + ServicePlan (atomic). Assigned Technician is deferred to M3. */
        CustomerUpdateInput: {
            name?: string;
            phone?: string | null;
            email?: string | null;
            addressLine?: string;
            postcode?: string;
            propertyType?: string | null;
            accessNotes?: string | null;
            riskNotes?: string | null;
            roundId?: string | null;
            price?: number;
            cleanMethod?: string | null;
            paymentMethod?: components["schemas"]["PaymentMethod"] | null;
        };
        /**
         * @example {
         *       "reason": "Customer Holiday/Away",
         *       "pauseStartDate": "2026-05-22",
         *       "pauseEndDate": "2026-06-22"
         *     }
         */
        PauseServiceInput: {
            /** @description Required by the UI; not persisted (no column). */
            reason: string;
            /** Format: date */
            pauseStartDate: string;
            /**
             * Format: date
             * @description null = indefinite pause.
             */
            pauseEndDate?: string | null;
        };
        /**
         * @example {
         *       "type": "INTERNAL",
         *       "body": "Prefers morning slots."
         *     }
         */
        NoteCreateInput: {
            type: components["schemas"]["NoteType"];
            body: string;
        };
    };
    responses: {
        /** @description Validation error, or POST /setup/complete with required steps missing. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, or expired Bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A mutating setup step was called after setup is already complete. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description POST /setup/complete when setup is already complete. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
