export type DebtStatusTab =
  | 'invoice-sent'
  | 'due-before'
  | 'failed-gc'
  | '7-days-over'
  | '14-days-over'
  | 'on-hold'
  | 'bad-debt'

export type DebtContactStatus = 'not-contacted' | 'contacted'

export type DebtPaymentMethod = 'GoCardless' | 'BACS' | 'Cash' | 'Standing Order'

export type DebtVisitPaymentStatus = 'paid' | 'unpaid'

export interface DebtRecentVisit {
  date: string
  amount: string
  paymentStatus: DebtVisitPaymentStatus
}

export interface DebtCustomerRecord {
  id: string
  customer: string
  address: string
  amountOwed: string
  amountValue: number
  paymentMethod: DebtPaymentMethod
  round: string
  status: DebtStatusTab
  contactStatus: DebtContactStatus
  lastContact?: string
  hasAlert?: boolean
  phone: string
  email: string
  invoiceDate: string
  daysOverdue: number
  gocardlessId?: string
  nextVisit: string
  nextCleanBlocked: boolean
  recentVisits: DebtRecentVisit[]
}

function visits(
  items: Array<[string, string, DebtVisitPaymentStatus]>,
): DebtRecentVisit[] {
  return items.map(([date, amount, paymentStatus]) => ({ date, amount, paymentStatus }))
}

export const debtPaymentContent = {
  title: 'Debt / Payment Risk Board',
  subtitle: 'Track overdue payments, failed collections, and customers at risk before the next clean',
  searchPlaceholder: 'Search customers by name, address, or postcode...',
  filters: {
    rounds: {
      label: 'All Rounds',
      options: [
        { value: 'all', label: 'All Rounds' },
        { value: 'alnwick-monday', label: 'Alnwick Monday' },
        { value: 'alnwick-wednesday', label: 'Alnwick Wednesday' },
        { value: 'bamburgh-tuesday', label: 'Bamburgh Tuesday' },
        { value: 'seahouses-thursday', label: 'Seahouses Thursday' },
      ],
    },
    methods: {
      label: 'Methods',
      options: [
        { value: 'all', label: 'All Methods' },
        { value: 'gocardless', label: 'GoCardless' },
        { value: 'bacs', label: 'BACS' },
        { value: 'cash', label: 'Cash' },
        { value: 'standing-order', label: 'Standing Order' },
      ],
    },
  },
  metrics: [
    {
      id: 'total-outstandings',
      label: 'Total Outstandings',
      value: '£2,264',
      helper: 'Across 27 customers',
      tone: 'accent',
    },
    {
      id: 'failed-gocardless',
      label: 'Failed GoCardless',
      value: '5',
      helper: 'Requires immediate follow-up',
      tone: 'danger',
    },
    {
      id: 'due-before-clean',
      label: 'Due Before Clean',
      value: '2',
      helper: 'Next clean within 7 days',
      tone: 'warning',
    },
    {
      id: 'hold-next-clean',
      label: 'Hold Next Clean',
      value: '5',
      helper: 'Blocked from next visit',
      tone: 'accent',
    },
    {
      id: 'bad-debt',
      label: 'Bad Debt',
      value: '£460',
      helper: 'Manually flagged',
      tone: 'danger',
    },
  ],
  statusTabs: [
    { id: 'invoice-sent', label: 'Invoice Sent', count: 6, hasAlert: false },
    { id: 'due-before', label: 'Due Before', count: 2, hasAlert: false },
    { id: 'failed-gc', label: 'Failed GC', count: 5, hasAlert: true },
    { id: '7-days-over', label: '7 Days Over', count: 4, hasAlert: true },
    { id: '14-days-over', label: '14 Days Over', count: 2, hasAlert: true },
    { id: 'on-hold', label: 'On Hold', count: 6, hasAlert: true },
    { id: 'bad-debt', label: 'Bad Debt', count: 2, hasAlert: true },
  ] satisfies { id: DebtStatusTab; label: string; count: number; hasAlert: boolean }[],
  resultsLabel: '{label} — {count} results',
  selectAll: 'Select all',
  actions: {
    sendReminder: 'Send Reminder',
    viewInvoice: 'View Invoice',
    moreOptions: 'More options',
  },
  contactLabels: {
    'not-contacted': 'Not yet contacted',
    contacted: 'Contacted',
  },
  lastContactLabel: 'Last contact: {when}',
  owedSuffix: 'owed',
  reminderToast: 'Reminder sent to {customer}',
  detailPanel: {
    sections: {
      paymentSummary: 'Payment Summary',
      nextCleanRisk: 'Next Clean Risk',
      contact: 'Contact',
      recentVisits: 'Recent Visits',
    },
    stats: {
      outstanding: 'Outstanding',
      overdue: 'Overdue',
      method: 'Method',
    },
    fields: {
      invoiceDate: 'Invoice Date',
      amountOwed: 'Amount Owed',
      daysOverdue: 'Days Overdue',
      paymentMethod: 'Payment Method',
      gocardlessId: 'GoCardless ID',
      round: 'Round',
      nextVisit: 'Next Visit',
      nextCleanBlocked: 'Next clean blocked?',
      lastContact: 'Last contact',
    },
    overdueEmpty: '—',
    notYetOverdue: 'Not yet overdue',
    blockedYes: 'Yes',
    blockedNo: 'No',
    completedVisit: 'Completed',
    visitPayment: {
      paid: 'Paid',
      unpaid: 'Unpaid',
    },
    actions: {
      sendReminder: 'Send Reminder',
      paymentLink: 'Payment Link',
      pauseService: 'Pause Service',
      resumeService: 'Resume Service',
      exportInvoice: 'Export Invoice or Download PDF',
    },
    toasts: {
      paymentLink: 'Payment link sent to {customer}',
      pauseService: 'Service paused for {customer}',
      resumeService: 'Service resumed for {customer}',
      exportInvoice: 'Invoice export started for {customer}',
    },
  },
  reminderModal: {
    title: 'Send Payment Reminder',
    toLabel: 'To',
    sendVia: 'Send via',
    channels: [
      { id: 'sms', label: 'SMS' },
      { id: 'whatsapp', label: 'WhatsApp' },
      { id: 'email', label: 'EMAIL' },
    ] as const,
    templateLabel: 'Template',
    messageLabel: 'Message',
    characterCount: '{count} characters',
    templates: [
      {
        value: 'gentle',
        label: 'Gentle Reminder',
        body: 'Hi {firstName}, just a friendly reminder that you have an outstanding balance of {amount} on your account. Please arrange payment at your earliest convenience. Thanks!',
      },
      {
        value: 'firm',
        label: 'Firm Reminder',
        body: 'Hi {firstName}, your account still has an outstanding balance of {amount}. Please settle payment soon to avoid interruption to your next clean. Thanks!',
      },
      {
        value: 'final',
        label: 'Final Notice',
        body: 'Hi {firstName}, this is a final reminder regarding your outstanding balance of {amount}. Please arrange payment immediately to keep your service active.',
      },
    ],
    actions: {
      cancel: 'Cancel',
      send: 'Send Reminder',
    },
    successToast: 'Reminder sent to {customer}',
  },
  paymentLinkModal: {
    title: 'Send Payment Link',
    fields: {
      customer: 'Customer',
      amount: 'Amount to collect',
      method: 'Payment Method',
      expiry: 'Link Expiry',
      message: 'Message to customer',
    },
    helper: 'A unique payment link will be generated and appended to the message automatically.',
    methods: [
      { value: 'stripe-link', label: 'Stripe Link' },
      { value: 'gocardless', label: 'GoCardless' },
      { value: 'bank-transfer', label: 'Bank Transfer' },
    ],
    expiryOptions: [
      { value: '3', label: '3 days' },
      { value: '7', label: '7 days' },
      { value: '14', label: '14 days' },
      { value: '30', label: '30 days' },
    ],
    defaultMessage:
      'Hi {firstName}, here is your secure payment link for {amount}. Please pay at your earliest convenience. Thank you.',
    actions: {
      cancel: 'Cancel',
      send: 'Generate & Send Link',
    },
    successToast: 'Payment link sent to {customer}',
  },
  pauseModal: {
    title: 'Pause Service',
    fields: {
      customer: 'Customer',
      reason: 'Reason',
      pauseFrom: 'Pause From',
    },
    reasons: [
      { value: 'outstanding', label: 'Outstanding Balance Unpaid' },
      { value: 'customer-request', label: 'Customer Request' },
      { value: 'failed-payment', label: 'Failed Payment' },
      { value: 'other', label: 'Other' },
    ],
    defaultPauseFrom: '2025-05-22',
    notifyLabel: 'Notify customer by SMS',
    notifyHelper: 'Send a message explaining the pause',
    defaultMessage:
      'Hi {firstName}, your window cleaning service has been temporarily paused due to an outstanding balance. Please contact us to arrange payment.',
    warning: 'Future visits will not be generated while this service is paused.',
    actions: {
      cancel: 'Cancel',
      pause: 'Pause Service',
    },
    successToast: 'Service paused for {customer}',
  },
  resumeModal: {
    title: 'Resume Service',
    fields: {
      customer: 'Customer',
      resumeFrom: 'Resume From',
      nextDue: 'Confirmed next due date',
    },
    defaultResumeFrom: '2025-06-01',
    defaultNextDue: '10/06/2026',
    notifyLabel: 'Notify customer of resumption',
    notifyHelper: 'Let them know service is back on',
    info: 'Visits will be regenerated from the resume date onwards.',
    actions: {
      cancel: 'Cancel',
      resume: 'Resume Service',
    },
    successToast: 'Service resumed for {customer}',
  },
  invoiceModal: {
    title: 'Invoice Preview',
    subtitle: '{customer} • {invoiceDate}',
    invoiceHeading: 'INVOICE',
    invoiceNumberPrefix: '#INV-2026-',
    billTo: 'BILL TO',
    invoiceDetails: 'INVOICE DETAILS',
    fields: {
      invoiceDate: 'Invoice Date',
      visitDate: 'Visit Date',
      dueDate: 'Due Date',
      payment: 'Payment',
    },
    table: {
      description: 'DESCRIPTION',
      technician: 'TECHNICIAN',
      amount: 'AMOUNT',
    },
    serviceTitle: 'Window Cleaning Service',
    serviceSubtitle: '{round} · {visitDate}',
    defaultTechnician: 'James Smith',
    totals: {
      subtotal: 'Subtotal',
      vat: 'VAT (0%)',
      totalDue: 'Total Due',
    },
    footer: 'Thank you for your business · RoundFlow · support@roundflow.co.uk',
    actions: {
      cancel: 'Cancel',
      print: 'Print',
      downloadPdf: 'Download PDF',
    },
    printToast: 'Print dialog opened',
    downloadToast: 'Invoice PDF download started',
  },
  records: [
    {
      id: 'debt-tom-richards',
      customer: 'Tom Richards',
      address: '5 Oak Avenue, NE61 1AB',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'GoCardless',
      round: 'Alnwick Monday',
      status: 'invoice-sent',
      contactStatus: 'not-contacted',
      phone: '07700 900123',
      email: 'tom.richards@email.com',
      invoiceDate: '20/05/2026',
      daysOverdue: 0,
      gocardlessId: 'PM000ABC123',
      nextVisit: '18 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['20/05/2026', '£35', 'unpaid'],
        ['20/04/2026', '£35', 'paid'],
        ['20/03/2026', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-sarah-mitchell',
      customer: 'Sarah Mitchell',
      address: '12 Willow Lane, NE66 2CD',
      amountOwed: '£42',
      amountValue: 42,
      paymentMethod: 'BACS',
      round: 'Alnwick Wednesday',
      status: 'invoice-sent',
      contactStatus: 'not-contacted',
      phone: '07700 900124',
      email: 'sarah.mitchell@email.com',
      invoiceDate: '3 Mar 2026',
      daysOverdue: 0,
      nextVisit: '19 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['3 Mar 2026', '£42', 'unpaid'],
        ['3 Feb 2026', '£42', 'paid'],
      ]),
    },
    {
      id: 'debt-james-cooper',
      customer: 'James Cooper',
      address: '8 Maple Street, NE67 3EF',
      amountOwed: '£28',
      amountValue: 28,
      paymentMethod: 'Cash',
      round: 'Bamburgh Tuesday',
      status: 'invoice-sent',
      contactStatus: 'not-contacted',
      phone: '07700 900125',
      email: 'james.cooper@email.com',
      invoiceDate: '1 Mar 2026',
      daysOverdue: 0,
      nextVisit: '17 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['1 Mar 2026', '£28', 'unpaid'],
        ['1 Feb 2026', '£28', 'paid'],
      ]),
    },
    {
      id: 'debt-emma-wilson',
      customer: 'Emma Wilson',
      address: '22 Chestnut Road, NE68 4GH',
      amountOwed: '£55',
      amountValue: 55,
      paymentMethod: 'Standing Order',
      round: 'Seahouses Thursday',
      status: 'invoice-sent',
      contactStatus: 'not-contacted',
      phone: '07700 900126',
      email: 'emma.wilson@email.com',
      invoiceDate: '4 Mar 2026',
      daysOverdue: 0,
      nextVisit: '20 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['4 Mar 2026', '£55', 'unpaid'],
        ['4 Feb 2026', '£55', 'paid'],
      ]),
    },
    {
      id: 'debt-robert-hall',
      customer: 'Robert Hall',
      address: '3 Birch Close, NE69 5IJ',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'GoCardless',
      round: 'Alnwick Monday',
      status: 'invoice-sent',
      contactStatus: 'contacted',
      lastContact: '1 day ago',
      phone: '07700 900127',
      email: 'robert.hall@email.com',
      invoiceDate: '28 Feb 2026',
      daysOverdue: 0,
      gocardlessId: 'PM000DEF456',
      nextVisit: '16 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['28 Feb 2026', '£35', 'unpaid'],
        ['28 Jan 2026', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-lisa-anderson',
      customer: 'Lisa Anderson',
      address: '17 Elm Drive, NE70 6KL',
      amountOwed: '£48',
      amountValue: 48,
      paymentMethod: 'BACS',
      round: 'Alnwick Wednesday',
      status: 'invoice-sent',
      contactStatus: 'not-contacted',
      phone: '07700 900128',
      email: 'lisa.anderson@email.com',
      invoiceDate: '5 Mar 2026',
      daysOverdue: 0,
      nextVisit: '21 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['5 Mar 2026', '£48', 'unpaid'],
        ['5 Feb 2026', '£48', 'paid'],
      ]),
    },
    {
      id: 'debt-due-1',
      customer: 'David Parker',
      address: '9 Pine Court, NE66 1AA',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'GoCardless',
      round: 'Alnwick Monday',
      status: 'due-before',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900129',
      email: 'david.parker@email.com',
      invoiceDate: '20 Feb 2026',
      daysOverdue: 5,
      gocardlessId: 'PM000GHI789',
      nextVisit: '15 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['20 Feb 2026', '£35', 'unpaid'],
        ['20 Jan 2026', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-due-2',
      customer: 'Helen Grant',
      address: '14 Ash Way, NE66 2BB',
      amountOwed: '£40',
      amountValue: 40,
      paymentMethod: 'Cash',
      round: 'Alnwick Wednesday',
      status: 'due-before',
      contactStatus: 'contacted',
      lastContact: '2 days ago',
      phone: '07700 900130',
      email: 'helen.grant@email.com',
      invoiceDate: '18 Feb 2026',
      daysOverdue: 7,
      nextVisit: '14 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['18 Feb 2026', '£40', 'unpaid'],
        ['18 Jan 2026', '£40', 'paid'],
      ]),
    },
    {
      id: 'debt-failed-1',
      customer: 'Michael Brown',
      address: '6 Cedar Grove, NE67 1CC',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'GoCardless',
      round: 'Bamburgh Tuesday',
      status: 'failed-gc',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900131',
      email: 'michael.brown@email.com',
      invoiceDate: '10 Feb 2026',
      daysOverdue: 12,
      gocardlessId: 'PM000JKL012',
      nextVisit: '13 Mar 2026',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['10 Feb 2026', '£35', 'unpaid'],
        ['10 Jan 2026', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-failed-2',
      customer: 'Anna Taylor',
      address: '11 Fir Place, NE67 2DD',
      amountOwed: '£60',
      amountValue: 60,
      paymentMethod: 'GoCardless',
      round: 'Seahouses Thursday',
      status: 'failed-gc',
      contactStatus: 'contacted',
      lastContact: '3 days ago',
      hasAlert: true,
      phone: '07700 900132',
      email: 'anna.taylor@email.com',
      invoiceDate: '8 Feb 2026',
      daysOverdue: 14,
      gocardlessId: 'PM000MNO345',
      nextVisit: '12 Mar 2026',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['8 Feb 2026', '£60', 'unpaid'],
        ['8 Jan 2026', '£60', 'paid'],
      ]),
    },
    {
      id: 'debt-failed-3',
      customer: 'Chris Evans',
      address: '2 Spruce Road, NE68 1EE',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'GoCardless',
      round: 'Alnwick Monday',
      status: 'failed-gc',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900133',
      email: 'chris.evans@email.com',
      invoiceDate: '12 Feb 2026',
      daysOverdue: 10,
      gocardlessId: 'PM000PQR678',
      nextVisit: '16 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['12 Feb 2026', '£35', 'unpaid'],
        ['12 Jan 2026', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-failed-4',
      customer: 'Nina Patel',
      address: '30 Beech Lane, NE68 2FF',
      amountOwed: '£45',
      amountValue: 45,
      paymentMethod: 'GoCardless',
      round: 'Alnwick Wednesday',
      status: 'failed-gc',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900134',
      email: 'nina.patel@email.com',
      invoiceDate: '9 Feb 2026',
      daysOverdue: 13,
      gocardlessId: 'PM000STU901',
      nextVisit: '18 Mar 2026',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['9 Feb 2026', '£45', 'unpaid'],
        ['9 Jan 2026', '£45', 'paid'],
      ]),
    },
    {
      id: 'debt-failed-5',
      customer: 'Paul Green',
      address: '19 Holly Street, NE69 1GG',
      amountOwed: '£38',
      amountValue: 38,
      paymentMethod: 'GoCardless',
      round: 'Bamburgh Tuesday',
      status: 'failed-gc',
      contactStatus: 'contacted',
      lastContact: '1 day ago',
      hasAlert: true,
      phone: '07700 900135',
      email: 'paul.green@email.com',
      invoiceDate: '11 Feb 2026',
      daysOverdue: 11,
      gocardlessId: 'PM000VWX234',
      nextVisit: '17 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['11 Feb 2026', '£38', 'unpaid'],
        ['11 Jan 2026', '£38', 'paid'],
      ]),
    },
    {
      id: 'debt-7-1',
      customer: 'Olivia White',
      address: '4 Poplar Avenue, NE70 1HH',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'BACS',
      round: 'Seahouses Thursday',
      status: '7-days-over',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900136',
      email: 'olivia.white@email.com',
      invoiceDate: '5 Feb 2026',
      daysOverdue: 8,
      nextVisit: '19 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['5 Feb 2026', '£35', 'unpaid'],
        ['5 Jan 2026', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-7-2',
      customer: 'Jack Lee',
      address: '25 Walnut Road, NE70 2II',
      amountOwed: '£50',
      amountValue: 50,
      paymentMethod: 'Standing Order',
      round: 'Alnwick Monday',
      status: '7-days-over',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900137',
      email: 'jack.lee@email.com',
      invoiceDate: '4 Feb 2026',
      daysOverdue: 9,
      nextVisit: '16 Mar 2026',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['4 Feb 2026', '£50', 'unpaid'],
        ['4 Jan 2026', '£50', 'paid'],
      ]),
    },
    {
      id: 'debt-7-3',
      customer: 'Sophie Clark',
      address: '7 Rowan Close, NE66 3JJ',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'Cash',
      round: 'Alnwick Wednesday',
      status: '7-days-over',
      contactStatus: 'contacted',
      lastContact: '5 days ago',
      hasAlert: true,
      phone: '07700 900138',
      email: 'sophie.clark@email.com',
      invoiceDate: '6 Feb 2026',
      daysOverdue: 7,
      nextVisit: '20 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['6 Feb 2026', '£35', 'unpaid'],
        ['6 Jan 2026', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-7-4',
      customer: 'Ryan Hughes',
      address: '16 Yew Terrace, NE67 3KK',
      amountOwed: '£42',
      amountValue: 42,
      paymentMethod: 'GoCardless',
      round: 'Bamburgh Tuesday',
      status: '7-days-over',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900139',
      email: 'ryan.hughes@email.com',
      invoiceDate: '3 Feb 2026',
      daysOverdue: 10,
      gocardlessId: 'PM000YZA567',
      nextVisit: '15 Mar 2026',
      nextCleanBlocked: false,
      recentVisits: visits([
        ['3 Feb 2026', '£42', 'unpaid'],
        ['3 Jan 2026', '£42', 'paid'],
      ]),
    },
    {
      id: 'debt-14-1',
      customer: 'Grace Adams',
      address: '10 Alder Street, NE68 3LL',
      amountOwed: '£70',
      amountValue: 70,
      paymentMethod: 'BACS',
      round: 'Seahouses Thursday',
      status: '14-days-over',
      contactStatus: 'contacted',
      lastContact: '1 week ago',
      hasAlert: true,
      phone: '07700 900140',
      email: 'grace.adams@email.com',
      invoiceDate: '25 Jan 2026',
      daysOverdue: 18,
      nextVisit: '22 Mar 2026',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['25 Jan 2026', '£70', 'unpaid'],
        ['25 Dec 2025', '£70', 'paid'],
      ]),
    },
    {
      id: 'debt-14-2',
      customer: 'Ben Foster',
      address: '21 Larch Lane, NE69 2MM',
      amountOwed: '£55',
      amountValue: 55,
      paymentMethod: 'GoCardless',
      round: 'Alnwick Monday',
      status: '14-days-over',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900141',
      email: 'ben.foster@email.com',
      invoiceDate: '26 Jan 2026',
      daysOverdue: 17,
      gocardlessId: 'PM000BCD890',
      nextVisit: '16 Mar 2026',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['26 Jan 2026', '£55', 'unpaid'],
        ['26 Dec 2025', '£55', 'paid'],
      ]),
    },
    {
      id: 'debt-hold-1',
      customer: 'Chloe Bennett',
      address: '13 Magnolia Way, NE70 3NN',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'GoCardless',
      round: 'Alnwick Wednesday',
      status: 'on-hold',
      contactStatus: 'contacted',
      lastContact: '2 days ago',
      hasAlert: true,
      phone: '07700 900142',
      email: 'chloe.bennett@email.com',
      invoiceDate: '15 Jan 2026',
      daysOverdue: 28,
      gocardlessId: 'PM000EFG123',
      nextVisit: 'Paused',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['15 Jan 2026', '£35', 'unpaid'],
        ['15 Dec 2025', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-hold-2',
      customer: 'Luke Morgan',
      address: '27 Acacia Road, NE66 4OO',
      amountOwed: '£40',
      amountValue: 40,
      paymentMethod: 'Cash',
      round: 'Bamburgh Tuesday',
      status: 'on-hold',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900143',
      email: 'luke.morgan@email.com',
      invoiceDate: '14 Jan 2026',
      daysOverdue: 29,
      nextVisit: 'Paused',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['14 Jan 2026', '£40', 'unpaid'],
        ['14 Dec 2025', '£40', 'paid'],
      ]),
    },
    {
      id: 'debt-hold-3',
      customer: 'Mia Reed',
      address: '1 Jasmine Close, NE67 4PP',
      amountOwed: '£48',
      amountValue: 48,
      paymentMethod: 'Standing Order',
      round: 'Seahouses Thursday',
      status: 'on-hold',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900144',
      email: 'mia.reed@email.com',
      invoiceDate: '12 Jan 2026',
      daysOverdue: 31,
      nextVisit: 'Paused',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['12 Jan 2026', '£48', 'unpaid'],
        ['12 Dec 2025', '£48', 'paid'],
      ]),
    },
    {
      id: 'debt-hold-4',
      customer: 'Noah Carter',
      address: '33 Violet Street, NE68 4QQ',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'BACS',
      round: 'Alnwick Monday',
      status: 'on-hold',
      contactStatus: 'contacted',
      lastContact: '4 days ago',
      hasAlert: true,
      phone: '07700 900145',
      email: 'noah.carter@email.com',
      invoiceDate: '10 Jan 2026',
      daysOverdue: 33,
      nextVisit: 'Paused',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['10 Jan 2026', '£35', 'unpaid'],
        ['10 Dec 2025', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-hold-5',
      customer: 'Ava Scott',
      address: '18 Daisy Drive, NE69 3RR',
      amountOwed: '£52',
      amountValue: 52,
      paymentMethod: 'GoCardless',
      round: 'Alnwick Wednesday',
      status: 'on-hold',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900146',
      email: 'ava.scott@email.com',
      invoiceDate: '8 Jan 2026',
      daysOverdue: 35,
      gocardlessId: 'PM000HIJ456',
      nextVisit: 'Paused',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['8 Jan 2026', '£52', 'unpaid'],
        ['8 Dec 2025', '£52', 'paid'],
      ]),
    },
    {
      id: 'debt-hold-6',
      customer: 'Ethan Price',
      address: '9 Lavender Path, NE70 4SS',
      amountOwed: '£35',
      amountValue: 35,
      paymentMethod: 'Cash',
      round: 'Bamburgh Tuesday',
      status: 'on-hold',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900147',
      email: 'ethan.price@email.com',
      invoiceDate: '7 Jan 2026',
      daysOverdue: 36,
      nextVisit: 'Paused',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['7 Jan 2026', '£35', 'unpaid'],
        ['7 Dec 2025', '£35', 'paid'],
      ]),
    },
    {
      id: 'debt-bad-1',
      customer: 'Isla Murphy',
      address: '15 Rose Gardens, NE66 5TT',
      amountOwed: '£220',
      amountValue: 220,
      paymentMethod: 'GoCardless',
      round: 'Seahouses Thursday',
      status: 'bad-debt',
      contactStatus: 'contacted',
      lastContact: '3 weeks ago',
      hasAlert: true,
      phone: '07700 900148',
      email: 'isla.murphy@email.com',
      invoiceDate: '10 Dec 2025',
      daysOverdue: 64,
      gocardlessId: 'PM000KLM789',
      nextVisit: 'Paused',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['10 Dec 2025', '£70', 'unpaid'],
        ['10 Nov 2025', '£75', 'unpaid'],
        ['10 Oct 2025', '£75', 'unpaid'],
      ]),
    },
    {
      id: 'debt-bad-2',
      customer: 'George Knight',
      address: '4 Orchid Close, NE67 5UU',
      amountOwed: '£240',
      amountValue: 240,
      paymentMethod: 'BACS',
      round: 'Alnwick Monday',
      status: 'bad-debt',
      contactStatus: 'not-contacted',
      hasAlert: true,
      phone: '07700 900149',
      email: 'george.knight@email.com',
      invoiceDate: '5 Dec 2025',
      daysOverdue: 69,
      nextVisit: 'Paused',
      nextCleanBlocked: true,
      recentVisits: visits([
        ['5 Dec 2025', '£80', 'unpaid'],
        ['5 Nov 2025', '£80', 'unpaid'],
        ['5 Oct 2025', '£80', 'unpaid'],
      ]),
    },
  ] satisfies DebtCustomerRecord[],
} as const
